### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by KunalDev** [lightningdevkit/ldk-swift#100]
Hello,

Demo Project is not working. So I created new project and added LDK Framework using SPM. Then I added project files for Polar connection. However I am getting compilation errors. Any suggestions @danielnordh ?

<img width="802" alt="Issues" src="https://user-images.githubusercontent.com/13748740/228665818-884a4925-d1b9-4ae4-b017-e84eda85656c.png">

**Comment by tnull** [comment]
Hum, could you clarify which demo project you're referring to? Also, do you mind trying to change the version number/tag in your `Package.swift` to version 0.0.114, in case it's still referring to 0.0.113?

**Comment by KunalDev** [comment]
@tnull Thank you for your reply.

DirectlyLinkedBindingsApp project (Polar integration sample) in current repository.  I updated Package.swift from 0.0.113 to 0.0.114. But still I am getting the same errors.

Moreover, I am beginner for Lighting. So Using LDK SDK can we achieve lighting functionalities (Create lighting address, Channel creation, Send and Receive payments) for iOS?

**Comment by tnull** [comment]
> DirectlyLinkedBindingsApp project (Polar integration sample) in current repository. I updated Package.swift from 0.0.113 to 0.0.114. But still I am getting the same errors.

Ah, did you try following the steps required for building the bindings yourself in the README? I don't think you can mix-and-match parts of the local LDK framework with the SPM version.
 
> Moreover, I am beginner for Lighting. So Using LDK SDK can we achieve lighting functionalities (Create lighting address, Channel creation, Send and Receive payments) for iOS?

Yes, although note that LDK will require you to implement and interconnect its different components, and you'll need to bring your own on-chain wallet to handle channel funding etc. For an easy start that handles all for you, you might want to look into LDK Node. A basic Rust version is already available at https://github.com/lightningdevkit/ldk-node, the Swift bindings are working but not reviewed/fully packaged yet, but hopefully they'll be merged and good to go in the coming weeks.

**Comment by tnull** [comment]
Closing this as it's stale. Feel free to reopen comment if the issue persists.
