### ISSUE TITLE
Add basic readme.md with installation instructions

### ISSUE THREAD

**Issue by danielnordh** [lightningdevkit/ldk-swift#15]
I'm looking to start using LDKin a new SwiftUI app and would really appreciate a brief installation and setup guide.

I found some documentation linked from the LDK website to [SwiftLightning](https://github.com/arik-so/SwiftLightning/tree/master/Documentation), but not sure if that is fully applicable here, and it doesn't mention the installation.

The [rn-ldk](https://github.com/BlueWallet/rn-ldk) repo is a good example of a basic guide (so I can probably grok the overview from there, but a dedicated one for idk-swift would save me and others time).

**Comment by cuhte3** [comment]
Same here! [SwiftLightning](https://github.com/arik-so/SwiftLightning) looks outdated. After exploring the repo it seems like there are a few steps to generate LDKFramework.xcframework to use in Swift app. So the installation guide might be like:

1. Install rustup (rust toolchain installer) and cargo (rust package manager). 
2. Clone [rust-lightning](https://github.com/lightningdevkit/rust-lightning), [ldk-c-bindings](https://github.com/lightningdevkit/ldk-c-bindings) and [idk-swift](https://github.com/lightningdevkit/ldk-swift) repos. 
3. In terminal navigate to your local /ldk-c-bindings folder and run `genbindings.sh 'path to your local rust-lightning'  'allow-std (bool)'`. This will generate static libraries `libldk.a` for all targets.
4. Navigate into your local idk-swift and run `compile_dependency_binaries.sh`. This will generate all dependencies needed to build xcframeworks.
5. Run `build_framework.sh`

Depend on your envieroment you might need add additional [targets](https://github.com/lightningdevkit/ldk-swift/blob/main/xcode/MISSING_STEPS.md)

@arik-so am I missing something?

**Comment by arik-so** [comment]
Thanks for the feedback! I've had rough documentation in `docs/setup.md`, but you're right, there should also be a general installation guide. I'll create a readme today or tomorrow.
