### ISSUE TITLE
Make available via Swift Package Manager

### ISSUE THREAD

**Issue by danielnordh** [lightningdevkit/ldk-swift#16]
Would be great to have the repo easily available in the standard ways for swift developers.
Top of my list would be Swift package manager, Cocoa Pods and Carthage less important for me personally but others might like that.

If I figure out how this repo is linked to the LDK source I might try and submit a PR for this, but at the moment I haven't wrapped my head around the code to see how easy or hard this would be.

**Comment by arik-so** [comment]
I agree, and would love some help with that. I've unfortunately had a lot of trouble with SPM so far.

**Comment by jurvis** [comment]
@danielnordh I can jump in here if you're not working on it 😄

**Comment by danielnordh** [comment]
Feel free @jurvis. I have not tried to make a package, mostly because I believe the build is automated.
