### ISSUE TITLE
Issues when using example setup code

### ISSUE THREAD

**Issue by danielnordh** [lightningdevkit/ldk-swift#17]
While attempting to set up LDK with the [setup instructions](https://github.com/lightningdevkit/ldk-swift/blob/main/docs/setup.md) in Xcode 13.2.1, I run into a bunch of errors and warnings.
Some easy to understand and fix, but some less so:

**Errors:**
`override func log(record: String?)` - does not override any function in super
`override func persist_new_channel(id: OutPoint, data: ChannelMonitor) -> Result_NoneChannelMonitorUpdateErrZ` - does not override any function in super
`override func update_persisted_channel(id: OutPoint, update: ChannelMonitorUpdate, data: ChannelMonitor) -> Result_NoneChannelMonitorUpdateErrZ` - does not override any function in super
`let txid = outpoint.get_txid()` - needs ? optional flag 
`let outputIndex = outpoint.get_index()` - needs ? optional flag
`let monitorBytes: [UInt8] = data.write(obj: data)` - Argument passed to call that takes no arguments

`chainMonitor = ChainMonitor.init(chain_source: filter, broadcaster: broadcaster, logger: logger, feeest: feeEstimator, persister: persister)` - Cannot convert value of type 'MyFilter' to expected argument type 'Option_FilterZ'

`let router = NetGraphMsgHandler(chain_access: nil, logger: logger, network_graph: networkGraph)` - 'nil' is not compatible with expected argument type 'Option_AccessZ', Argument 'network_graph' must precede argument 'chain_access'

`let peerManager = PeerManager(message_handler: messageHandler, our_node_secret: nodeSecret, ephemeral_random_data: peerManagerSeed, logger: logger)` - Missing argument for parameter 'custom_message_handler' in call

**Warnings:**
`print("record: \(record)")` - need to account for optional
`keyData.withUnsafeMutableBytes {SecRandomCopyBytes(kSecRandomDefault, 32, $0.baseAddress!)} ` - Result of call to 'withUnsafeMutableBytes' is unused
`let chainParameters = ChainParameters(network_arg: LDKNetwork_Bitcoin, best_block_arg: bestBlock)` - 'init(network_arg:best_block_arg:)' is deprecated: This method passes non-cloneable objects by owned value. Here be dragons.
`keyData2.withUnsafeMutableBytes {SecRandomCopyBytes(kSecRandomDefault, 32, $0.baseAddress!)}` - Result of call to 'withUnsafeMutableBytes' is unused

I found myself writing a wrapper 'LDKManager' class for all this boilerplate and it would be nice if something like that was included in the library. Requiring only a LDKManager.init() call with any relevant variables to get started.

**Comment by arik-so** [comment]
I have updated the docs to reflect usage of the `ChannelManagerConstructor` helper class. I think it probably has a lot of overlap with your `LDKManager` class. Unfortunately, a lot of the boilerplate is trait overrides, but we have been considering using an `LDKNode` class of sorts, that would have most of the default objects and managers bundled together.

**Comment by danielnordh** [comment]
Using the updated instructions from #19 :

**Errors**
`print("log event: \(record.get_args())")` - Value of type 'String?' has no member 'get_args' (I'm using this instead `print("record: \(String(describing: record))")`)

`let chainMonitor = ChainMonitor(chain_source: filterOption.dangle(), broadcaster: broadcaster, logger: logger, feeest: feeEstimator, persister: persister)` - Value of type 'Option_FilterZ' has no member 'dangle'
If I remove .dangle(), the error disappears but I get this warning instead - 'init(chain_source:broadcaster:logger:feeest:persister:)' is deprecated: This method passes non-cloneable objects by owned value. Here be dragons.

`let keysInterface = keysManager.as_KeysInterface()` - invalid redeclaration (it's listed twice in the setup guide)

`current_blockchain_tip_height: latestBlockHeight,` - Cannot convert value of type 'Int' to expected argument type 'UInt32' (I'm using `UInt32(latestBlockHeight)`)

`let serializedChannelManager: [UInt8] = channelManager.write(obj: channelManager)` - argument passed to call that takes no argument (I'm trying with `channelManager.write()` which gets rid of the error)

I could get past most of these errors and get the project to build.

**Warnings**
A bunch of unused variables

**Consol log output**
Here's the log output following the setup:

```
deiniting ChannelManagerConstructor
FeeEstimator::free should be overridden!
BroadcasterInterface::free should be overridden!
Logger::free should be overridden!
Logger::free should be overridden!
Filter::free should be overridden!
BroadcasterInterface::free should be overridden!
Logger::free should be overridden!
FeeEstimator::free should be overridden!
Persist::free should be overridden!
Filter::free should be overridden!
```

Do you have recommendations for good defaults for the above, and could it be included in the setup guide?
