### ISSUE TITLE
ProbabilisticScorer.read() - parameters not named correctly

### ISSUE THREAD

**Issue by danielnordh** [lightningdevkit/ldk-swift#91]
The parameter names are not very helpful here.
I presume they should reflect the expected types as on other platforms.

```swift
let scoreResult = ProbabilisticScorer.read(ser: <#T##[UInt8]#>, argA: <#T##Bindings.ProbabilisticScoringParameters#>, argB: <#T##Bindings.NetworkGraph#>, argC: <#T##Bindings.Logger#>)
```

ser - ?
argA - `ProbabilisticScoringParameters`
argB - `NetworkGraph`
argC - `Logger`

**Comment by arik-so** [comment]
Thanks for raising this! The variable names are actually taken automatically from the C bindings, and while we could special-case it here, I think that would be opening up a can of worms. I'll move this issue to the upstream repository and close it here with wontfix if that's all right.
