### ISSUE TITLE
Introduce formatter in generation and CI

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/ldk-swift#99]
We may want to introduce running `swiftformat`/https://github.com/apple/swift-format as a final step of code generation, as well as enforcing it for all (generated and non-generated) files in CI.

**Comment by arik-so** [comment]
I didn't realize swift-format existed. When looking for Swift linters, I had previously only been seeing third party libraries. We should definitely incorporate it into the generator.

**Comment by tnull** [comment]
Closing as done in #111.
